import fs from 'node:fs/promises';
import path from 'node:path';
import type { Database } from '../db/sqlite';
import { namedParams } from '../db/sqlite';

export interface AgentInstructionSource {
    agentId: string;
    agentName: string;
    notes: string;
    soul: string;
    updatedAt: string;
    workspaceDir: string;
}

export interface AgentInstructionRenderResult {
    content: string;
    renderedAt: string;
    sha256: string;
}

export const generatedInstructionFileName = 'AGENTS.md';

const defaultAgentName = 'main';
const defaultAgentId = 'main';

const tavernManagedInstructions = `You are operating inside Tavern, a local always-on app for working with agents in durable chats.

Tavern chat history is the product timeline. OpenClaw sessions and turns are execution details behind that timeline. Use Tavern chat identity when talking about conversations, and use runtime session details only when execution evidence matters.

Cortex is Tavern's durable knowledgebase and long-term memory. Use Cortex tools when remembered project context, user preferences, prior decisions, source-backed notes, or known corrections may change the answer. Use cortex_recall before answering when earlier durable context may matter and is not already present in the current chat. Do not use Cortex for self-contained questions, transient chat, or facts that must come from current runtime state or an external source. Current user instructions and current source material override remembered Cortex context.

Use cortex_get_page when a specific wiki page, slug, concept, person, project, file, or source is named and the maintained page matters. Use cortex_search for exact-term lookup. Use cortex_list_backlinks when wiki relationships or graph context matter.

Use cortex_capture when the user confirms a durable preference, decision, correction, source-backed observation, project fact, or reusable note. Keep captures small, inspectable, and source-linked. Do not capture guesses, broad chat dumps, secrets, or sensitive material without a clear user reason.

This AGENTS.md file is generated by Tavern. Do not edit it directly. To update your own durable operating notes, use the Tavern workspace notes tools.`;

export function ensureWorkspaceInstructionSchema(db: Database) {
    db.exec(`
CREATE TABLE IF NOT EXISTS workspace_agent_instructions (
  agent_id TEXT PRIMARY KEY,
  agent_name TEXT NOT NULL,
  workspace_dir TEXT NOT NULL,
  soul TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  rendered_hash TEXT,
  rendered_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
`);
}

export function getAgentInstructionSource(
    db: Database,
    agentId: string
): AgentInstructionSource | null {
    const row = db
        .prepare(
            `SELECT agent_id, agent_name, workspace_dir, soul, notes, updated_at
             FROM workspace_agent_instructions
             WHERE agent_id = ?`
        )
        .get(agentId) as
        | {
              agent_id: string;
              agent_name: string;
              notes: string;
              soul: string;
              updated_at: string;
              workspace_dir: string;
          }
        | undefined;

    return row
        ? {
              agentId: row.agent_id,
              agentName: row.agent_name,
              notes: row.notes,
              soul: row.soul,
              updatedAt: row.updated_at,
              workspaceDir: row.workspace_dir,
          }
        : null;
}

export function updateAgentInstructionSource(
    db: Database,
    input: {
        agentId?: string | null;
        agentName?: string | null;
        soul?: string | null;
        workspaceDir: string;
    }
) {
    const timestamp = new Date().toISOString();
    const existing = getAgentInstructionSource(db, input.agentId ?? defaultAgentId);
    const source = {
        agentId: input.agentId?.trim() || defaultAgentId,
        agentName: input.agentName?.trim() || existing?.agentName || defaultAgentName,
        notes: existing?.notes ?? '',
        soul: input.soul?.trim() ?? existing?.soul ?? '',
        workspaceDir: input.workspaceDir,
    };

    db.prepare(
        `INSERT INTO workspace_agent_instructions (
            agent_id, agent_name, workspace_dir, soul, notes, created_at, updated_at
        ) VALUES (
            $agentId, $agentName, $workspaceDir, $soul, $notes, $timestamp, $timestamp
        )
        ON CONFLICT(agent_id) DO UPDATE SET
            agent_name = excluded.agent_name,
            workspace_dir = excluded.workspace_dir,
            soul = excluded.soul,
            updated_at = excluded.updated_at`
    ).run(namedParams({ ...source, timestamp }));

    return getAgentInstructionSource(db, source.agentId) as AgentInstructionSource;
}

export function updateAgentNotes(
    db: Database,
    input: {
        agentId?: string | null;
        notes: string;
        workspaceDir?: string | null;
    }
) {
    const timestamp = new Date().toISOString();
    const agentId = input.agentId?.trim() || defaultAgentId;
    const existing = getAgentInstructionSource(db, agentId);
    const workspaceDir = input.workspaceDir?.trim() || existing?.workspaceDir;

    if (!workspaceDir) {
        throw new Error(`No managed workspace is registered for agent "${agentId}".`);
    }

    db.prepare(
        `INSERT INTO workspace_agent_instructions (
            agent_id, agent_name, workspace_dir, soul, notes, created_at, updated_at
        ) VALUES (
            $agentId, $agentName, $workspaceDir, $soul, $notes, $timestamp, $timestamp
        )
        ON CONFLICT(agent_id) DO UPDATE SET
            notes = excluded.notes,
            updated_at = excluded.updated_at`
    ).run(
        namedParams({
            agentId,
            agentName: existing?.agentName ?? defaultAgentName,
            notes: normalizeNotes(input.notes),
            soul: existing?.soul ?? '',
            timestamp,
            workspaceDir,
        })
    );

    return getAgentInstructionSource(db, agentId) as AgentInstructionSource;
}

export async function renderAgentInstructions(db: Database, agentId = defaultAgentId) {
    const source = getAgentInstructionSource(db, agentId);

    if (!source) {
        throw new Error(`No managed workspace is registered for agent "${agentId}".`);
    }

    const renderedAt = new Date().toISOString();
    const content = composeAgentInstructions(source);
    const sha256 = await hashText(content);
    const agentsPath = path.join(source.workspaceDir, generatedInstructionFileName);

    await fs.mkdir(source.workspaceDir, { recursive: true });
    await fs.writeFile(agentsPath, content, { mode: 0o600 });
    db.prepare(
        `UPDATE workspace_agent_instructions
         SET rendered_at = $renderedAt, rendered_hash = $sha256, updated_at = $renderedAt
         WHERE agent_id = $agentId`
    ).run(namedParams({ agentId: source.agentId, renderedAt, sha256 }));

    return { content, renderedAt, sha256 } satisfies AgentInstructionRenderResult;
}

export function composeAgentInstructions(
    source: Pick<AgentInstructionSource, 'agentName' | 'notes' | 'soul'>
) {
    const sections = [
        '# Tavern Agent Instructions',
        `You are ${source.agentName}, a Tavern-managed agent.`,
        tavernManagedInstructions,
        formatOptionalParagraph(source.soul),
        formatOptionalParagraph(source.notes),
    ].filter((section): section is string => Boolean(section));

    return `${sections.join('\n\n')}\n`;
}

function formatOptionalParagraph(value: string) {
    const normalized = value.trim();
    return normalized.length > 0 ? normalized : null;
}

function normalizeNotes(value: string) {
    return value.trim().slice(0, 20_000);
}

async function hashText(value: string) {
    const data = new TextEncoder().encode(value);
    const digest = await crypto.subtle.digest('SHA-256', data);
    return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, '0')).join('');
}
