import { mkdtemp, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, test } from 'vitest';
import { closeDb, getDb, initTestDb } from '../db/connection';
import { ensureRuntimeSchema } from '../db/schema';
import { subscribeToRuntimeEvents } from '../tavern/runtime-events';
import {
    generateAgentInstructions,
    generatedInstructionFileName,
    generateRegisteredAgentInstructions,
    getAgentWorkspaceSource,
    hermesBootstrapFileNamesToClear,
    registerAgentWorkspace,
} from './instructions';
import { agentNotesFileName, renderAgentInstructions } from './managed-instructions';
import { handleWorkspaceRequest } from './routes';

describe('generated agent instructions', () => {
    let workspaceDir: string;

    beforeEach(async () => {
        workspaceDir = await mkdtemp(path.join(tmpdir(), 'tavern-workspace-instructions-'));
        ensureRuntimeSchema(initTestDb());
    });

    afterEach(async () => {
        closeDb();
        await rm(workspaceDir, { force: true, recursive: true });
    });

    function registerPlanner() {
        return registerAgentWorkspace(getDb(), {
            agentId: 'planner',
            agentName: 'Planner',
            workspaceDir,
        });
    }

    async function readAgentsFile() {
        return await readFile(path.join(workspaceDir, generatedInstructionFileName), 'utf8');
    }

    async function readNotesFile() {
        return await readFile(path.join(workspaceDir, agentNotesFileName), 'utf8');
    }

    test('generates AGENTS.md and seeds NOTES.md on first run', async () => {
        registerPlanner();

        const result = await generateAgentInstructions(getDb(), 'planner');
        const content = await readAgentsFile();

        expect(result.written).toBe(true);
        expect(result.sha256).toMatch(/^[a-f0-9]{64}$/u);
        expect(content).toBe(result.content);
        expect(content).toMatch(/^<!-- GENERATED BY TAVERN/u);
        expect(content).toContain('You are Planner, the resident agent of Tavern');
        await expect(readNotesFile()).resolves.toContain('Durable notes, instructions');
    });

    test('tells the agent AGENTS.md is immutable and NOTES.md is its scratch space', () => {
        const content = renderAgentInstructions('Planner', '');

        expect(content).not.toMatch(/hermes/iu);
        expect(content).toContain('## This File Is Generated');
        expect(content).toContain('Never edit AGENTS.md');
        expect(content).toContain('`NOTES.md`');
        expect(content).toContain('`SOUL.md`');
        expect(content).toContain('use the `tavern` skill');
        expect(content).toContain('## Environment');
        expect(content).toContain('## Visible Progress');
        expect(content).toContain('send one short preamble');
        expect(content).toContain('send a brief update');
        expect(content).toContain('## Delegation');
        expect(content).toContain("Cortex is Tavern's durable knowledge store");
        expect(content).toContain('Tavern maintains the wiki automatically');
        expect(content).toContain('Never park wiki work on the user');
    });

    test('generation is deterministic and only writes on change', async () => {
        const events: unknown[] = [];
        const unsubscribe = subscribeToRuntimeEvents((event) => events.push(event));

        try {
            registerPlanner();
            const first = await generateAgentInstructions(getDb(), 'planner');
            const second = await generateAgentInstructions(getDb(), 'planner');

            expect(first.written).toBe(true);
            expect(second.written).toBe(false);
            expect(second.content).toBe(first.content);
            expect(events).toHaveLength(1);
        } finally {
            unsubscribe();
        }
    });

    test('the generated file is read-only and direct writes fail', async () => {
        registerPlanner();
        await generateAgentInstructions(getDb(), 'planner');

        const agentsPath = path.join(workspaceDir, generatedInstructionFileName);
        const mode = (await stat(agentsPath)).mode & 0o777;
        expect(mode).toBe(0o444);
        await expect(writeFile(agentsPath, 'agent scribbles')).rejects.toThrow();
    });

    test('composes NOTES.md content into the Notes section', async () => {
        registerPlanner();
        await generateAgentInstructions(getDb(), 'planner');
        await writeFile(
            path.join(workspaceDir, agentNotesFileName),
            '# Notes\n\nAlways use bun, never npm.\n'
        );

        const result = await generateAgentInstructions(getDb(), 'planner');

        expect(result.written).toBe(true);
        expect(result.content).toContain('## Notes');
        expect(result.content).toContain('Always use bun, never npm.');
    });

    test('never writes NOTES.md after seeding', async () => {
        registerPlanner();
        await generateAgentInstructions(getDb(), 'planner');
        const agentNotes = '# Notes\n\nMine, not yours.\n';
        await writeFile(path.join(workspaceDir, agentNotesFileName), agentNotes);

        await generateAgentInstructions(getDb(), 'planner');
        await generateAgentInstructions(getDb(), 'planner');

        await expect(readNotesFile()).resolves.toBe(agentNotes);
    });

    test('migrates legacy managed-block AGENTS.md content into NOTES.md', async () => {
        const userContent = '# My Rules\n\nKeep responses short.';
        await writeFile(
            path.join(workspaceDir, generatedInstructionFileName),
            `<!-- tavern:managed v=0123456789abcdef -->\nold managed text\n<!-- /tavern:managed -->\n\n${userContent}\n`
        );
        registerPlanner();

        const result = await generateAgentInstructions(getDb(), 'planner');

        await expect(readNotesFile()).resolves.toBe(`${userContent}\n`);
        expect(result.content).not.toContain('old managed text');
        expect(result.content).not.toContain('tavern:managed');
        expect(result.content).toContain('Keep responses short.');
    });

    test('migrates a fully hand-written legacy AGENTS.md into NOTES.md', async () => {
        const legacy = '# Hand written\n\nNo markers at all.\n';
        await writeFile(path.join(workspaceDir, generatedInstructionFileName), legacy);
        registerPlanner();

        await generateAgentInstructions(getDb(), 'planner');

        await expect(readNotesFile()).resolves.toBe(legacy);
    });

    test('rename regenerates with the new agent name', async () => {
        registerPlanner();
        await generateAgentInstructions(getDb(), 'planner');

        registerAgentWorkspace(getDb(), {
            agentId: 'planner',
            agentName: 'Navigator',
            workspaceDir,
        });
        const result = await generateAgentInstructions(getDb(), 'planner');

        expect(result.written).toBe(true);
        expect(result.content).toContain('You are Navigator, the resident agent of Tavern');
    });

    test('generation clears legacy bootstrap files but never SOUL.md', async () => {
        await Promise.all(
            hermesBootstrapFileNamesToClear.map((fileName) =>
                writeFile(path.join(workspaceDir, fileName), 'legacy bootstrap')
            )
        );
        await writeFile(path.join(workspaceDir, 'SOUL.md'), 'identity');
        registerPlanner();

        await generateAgentInstructions(getDb(), 'planner');

        await Promise.all(
            hermesBootstrapFileNamesToClear.map((fileName) =>
                expect(readFile(path.join(workspaceDir, fileName), 'utf8')).resolves.toBe('')
            )
        );
        await expect(readFile(path.join(workspaceDir, 'SOUL.md'), 'utf8')).resolves.toBe(
            'identity'
        );
    });

    test('registered-only generation skips unknown agents', async () => {
        await expect(
            generateRegisteredAgentInstructions(getDb(), 'unknown-agent')
        ).resolves.toBeNull();

        registerPlanner();
        const result = await generateRegisteredAgentInstructions(getDb(), 'planner');
        expect(result?.written).toBe(true);
    });

    test('register preserves the stored agent name when omitted', () => {
        registerPlanner();
        registerAgentWorkspace(getDb(), { agentId: 'planner', workspaceDir });

        expect(getAgentWorkspaceSource(getDb(), 'planner')).toMatchObject({
            agentId: 'planner',
            agentName: 'Planner',
            workspaceDir,
        });
    });

    test('instructions GET route returns the generated AGENTS.md file', async () => {
        registerPlanner();
        await generateAgentInstructions(getDb(), 'planner');

        const response = await handleWorkspaceRequest(
            new Request('http://runtime.test/workspace/agents/planner/instructions')
        );
        const body = (await response?.json()) as { content: string; path: string };

        expect(response?.status).toBe(200);
        expect(body.path).toBe(generatedInstructionFileName);
        expect(body.content).toContain('You are Planner, the resident agent of Tavern');
    });

    test('instructions PUT route registers the workspace and generates the file', async () => {
        const response = await handleWorkspaceRequest(
            new Request('http://runtime.test/workspace/agents/planner/instructions', {
                body: JSON.stringify({ agentName: 'Planner', workspaceDir }),
                headers: { 'content-type': 'application/json' },
                method: 'PUT',
            })
        );
        const body = (await response?.json()) as {
            agentId: string;
            renderedAt: string;
            sha256: string;
            updatedAt: string;
        };

        expect(response?.status).toBe(200);
        expect(body.agentId).toBe('planner');
        expect(body.sha256).toMatch(/^[a-f0-9]{64}$/u);
        expect(Date.parse(body.renderedAt)).not.toBeNaN();

        await expect(readAgentsFile()).resolves.toContain(
            'You are Planner, the resident agent of Tavern'
        );
    });
});
