import fs from 'node:fs/promises';
import path from 'node:path';
import { defaultCortexPageTypes } from '@tavern/api';
import type { Database } from '../db/sqlite';
import { namedParams } from '../db/sqlite';

export interface AgentInstructionSource {
    agentId: string;
    agentName: string;
    notes: string;
    updatedAt: string;
    userInstructions: string;
    workspaceDir: string;
}

export interface AgentInstructionRenderResult {
    content: string;
    renderedAt: string;
    sha256: string;
}

export const generatedInstructionFileName = 'AGENTS.md';
export const openClawBootstrapFileNamesToClear = [
    'BOOTSTRAP.md',
    'HEARTBEAT.md',
    'IDENTITY.md',
    'MEMORY.md',
    'ROLE.md',
    'SOUL.md',
    'TOOLS.md',
    'USER.md',
] as const;

const defaultAgentName = 'main';
const defaultAgentId = 'main';

const tavernManagedInstructions = `You are operating inside Tavern, a local always-on app for working with agents in durable chats.

Tavern chat history is the product timeline. OpenClaw sessions and turns are execution details behind that timeline. Use Tavern chat identity when talking about conversations, and use runtime session details only when execution evidence matters.

Cortex is Tavern's durable knowledgebase and long-term memory. Use Cortex tools when remembered project context, user preferences, prior decisions, source-backed notes, or known corrections may change the answer. Do not use Cortex for self-contained questions, transient chat, or facts that must come from current runtime state or an external source. Current user instructions and current source material override remembered Cortex context.

Follow Tavern's Cortex operating resources: resolver, brain-ops, signal detector, and conventions. They define when to search, recall, capture, inspect backlinks, and preserve contradictions.

Choose the lightest Cortex lookup that can answer the task. Use cortex_get_page when you know the exact page or slug; it returns the full compiled truth and timeline. Use cortex_search for exact names, slugs, keywords, and "do we know anything about X?" checks; search returns snippets, so load the full page when the snippet confirms relevance and page context matters. Use cortex_recall with conservative mode for narrow fact checks. Use cortex_recall with balanced mode by default when prior memory may affect the answer. Use cortex_recall with tokenmax mode only for broad memory synthesis where missing older context would materially change the work: strategy, planning, audits, contradictions, recurring decisions, project history, or "what do we know about X?" style questions.

For conflicts, the user's current direct statement wins, then Cortex compiled truth, then Cortex timeline evidence, then external sources. If recalled Cortex context materially affects your answer, mention the page or source basis. Use cortex_list_backlinks when wiki relationships or graph context matter.

Use cortex_capture when the user confirms a durable preference, decision, correction, source-backed observation, project fact, or reusable note. Keep captures small, inspectable, and source-linked. Do not capture guesses, broad chat dumps, secrets, or sensitive material without a clear user reason.

Default Cortex page types: ${defaultCortexPageTypes.join(', ')}. Prefer these unless the active Cortex schema or user direction calls for a different type.

This AGENTS.md file is generated by Tavern. Do not edit it directly. To update your own durable operating notes, use the Tavern workspace notes tools.`;

export function ensureWorkspaceInstructionSchema(db: Database) {
    db.exec(`
CREATE TABLE IF NOT EXISTS workspace_agent_instructions (
  agent_id TEXT PRIMARY KEY,
  agent_name TEXT NOT NULL,
  workspace_dir TEXT NOT NULL,
  user_instructions TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  rendered_hash TEXT,
  rendered_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
`);
    try {
        db.exec(
            'ALTER TABLE workspace_agent_instructions RENAME COLUMN soul TO user_instructions;'
        );
    } catch {
        /* column already migrated or table is fresh */
    }
    try {
        db.exec(
            `ALTER TABLE workspace_agent_instructions ADD COLUMN user_instructions TEXT NOT NULL DEFAULT '';`
        );
    } catch {
        /* column already exists */
    }
}

export function getAgentInstructionSource(
    db: Database,
    agentId: string
): AgentInstructionSource | null {
    const row = db
        .prepare(
            `SELECT agent_id, agent_name, workspace_dir, user_instructions, notes, updated_at
             FROM workspace_agent_instructions
             WHERE agent_id = ?`
        )
        .get(agentId) as
        | {
              agent_id: string;
              agent_name: string;
              notes: string;
              updated_at: string;
              user_instructions: string;
              workspace_dir: string;
          }
        | undefined;

    return row
        ? {
              agentId: row.agent_id,
              agentName: row.agent_name,
              notes: row.notes,
              updatedAt: row.updated_at,
              userInstructions: row.user_instructions,
              workspaceDir: row.workspace_dir,
          }
        : null;
}

export function updateAgentInstructionSource(
    db: Database,
    input: {
        agentId?: string | null;
        agentName?: string | null;
        userInstructions?: string | null;
        workspaceDir: string;
    }
) {
    const timestamp = new Date().toISOString();
    const existing = getAgentInstructionSource(db, input.agentId ?? defaultAgentId);
    const userInstructions =
        input.userInstructions !== undefined
            ? (input.userInstructions?.trim() ?? existing?.userInstructions ?? '')
            : (existing?.userInstructions ?? '');
    const source = {
        agentId: input.agentId?.trim() || defaultAgentId,
        agentName: input.agentName?.trim() || existing?.agentName || defaultAgentName,
        notes: existing?.notes ?? '',
        userInstructions,
        workspaceDir: input.workspaceDir,
    };

    db.prepare(
        `INSERT INTO workspace_agent_instructions (
            agent_id, agent_name, workspace_dir, user_instructions, notes, created_at, updated_at
        ) VALUES (
            $agentId, $agentName, $workspaceDir, $userInstructions, $notes, $timestamp, $timestamp
        )
        ON CONFLICT(agent_id) DO UPDATE SET
            agent_name = excluded.agent_name,
            workspace_dir = excluded.workspace_dir,
            user_instructions = excluded.user_instructions,
            updated_at = excluded.updated_at`
    ).run(
        namedParams({
            agentId: source.agentId,
            agentName: source.agentName,
            notes: source.notes,
            timestamp,
            userInstructions: source.userInstructions,
            workspaceDir: source.workspaceDir,
        })
    );

    return getAgentInstructionSource(db, source.agentId) as AgentInstructionSource;
}

export function updateAgentNotes(
    db: Database,
    input: {
        agentId?: string | null;
        notes: string;
        workspaceDir?: string | null;
    }
) {
    const timestamp = new Date().toISOString();
    const agentId = input.agentId?.trim() || defaultAgentId;
    const existing = getAgentInstructionSource(db, agentId);
    const workspaceDir = input.workspaceDir?.trim() || existing?.workspaceDir;

    if (!workspaceDir) {
        throw new Error(`No managed workspace is registered for agent "${agentId}".`);
    }

    db.prepare(
        `INSERT INTO workspace_agent_instructions (
            agent_id, agent_name, workspace_dir, user_instructions, notes, created_at, updated_at
        ) VALUES (
            $agentId, $agentName, $workspaceDir, $userInstructions, $notes, $timestamp, $timestamp
        )
        ON CONFLICT(agent_id) DO UPDATE SET
            notes = excluded.notes,
            updated_at = excluded.updated_at`
    ).run(
        namedParams({
            agentId,
            agentName: existing?.agentName ?? defaultAgentName,
            notes: normalizeNotes(input.notes),
            timestamp,
            userInstructions: existing?.userInstructions ?? '',
            workspaceDir,
        })
    );

    return getAgentInstructionSource(db, agentId) as AgentInstructionSource;
}

export async function renderAgentInstructions(db: Database, agentId = defaultAgentId) {
    const source = getAgentInstructionSource(db, agentId);

    if (!source) {
        throw new Error(`No managed workspace is registered for agent "${agentId}".`);
    }

    const renderedAt = new Date().toISOString();
    const content = composeAgentInstructions(source);
    const sha256 = await hashText(content);
    const agentsPath = path.join(source.workspaceDir, generatedInstructionFileName);

    await fs.mkdir(source.workspaceDir, { recursive: true });
    await fs.writeFile(agentsPath, content, { mode: 0o600 });
    db.prepare(
        `UPDATE workspace_agent_instructions
         SET rendered_at = $renderedAt, rendered_hash = $sha256, updated_at = $renderedAt
         WHERE agent_id = $agentId`
    ).run(namedParams({ agentId: source.agentId, renderedAt, sha256 }));

    return { content, renderedAt, sha256 } satisfies AgentInstructionRenderResult;
}

export async function clearOpenClawBootstrapFiles(workspaceDir: string) {
    await Promise.all(
        openClawBootstrapFileNamesToClear.map((fileName) =>
            fs.writeFile(path.join(workspaceDir, fileName), '', { mode: 0o600 })
        )
    );
}

export function composeAgentInstructions(
    source: Pick<AgentInstructionSource, 'agentName' | 'notes' | 'userInstructions'>
) {
    const sections = [
        '# Tavern Agent Instructions',
        `You are ${source.agentName}, a Tavern-managed agent.`,
        tavernManagedInstructions,
        formatOptionalParagraph(source.userInstructions),
        formatOptionalParagraph(source.notes),
    ].filter((section): section is string => Boolean(section));

    return `${sections.join('\n\n')}\n`;
}

function formatOptionalParagraph(value: string) {
    const normalized = value.trim();
    return normalized.length > 0 ? normalized : null;
}

function normalizeNotes(value: string) {
    return value.trim().slice(0, 20_000);
}

async function hashText(value: string) {
    const data = new TextEncoder().encode(value);
    const digest = await crypto.subtle.digest('SHA-256', data);
    return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, '0')).join('');
}
