[install]
exact = true
auto = "disable"
saveTextLockfile = true
minimumReleaseAge = 259200

[install.scopes]
'@hugeicons-pro' = { token = '$HUGEICONS_LICENSE_KEY', url = 'https://npm.hugeicons.com/' }
