import { describe, expect, it } from 'bun:test';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { targetsGeneratedInstructionFile } from './generated-file-guard.js';
import { TAVERN_WORKSPACE_TOOL_NAMES } from './tool-contracts.js';
import { registerWorkspaceNotesTools } from './workspace-notes-tools.js';

describe('Tavern Workspace tools', () => {
    it('declares the registered tools in the OpenClaw manifest', () => {
        expect(readManifestToolNames()).toEqual(TAVERN_WORKSPACE_TOOL_NAMES);
    });

    it('registers agent notes tools', () => {
        const tools = [];

        registerWorkspaceNotesTools(
            {
                registerTool(tool) {
                    tools.push(tool.name);
                },
            },
            { baseUrl: 'http://127.0.0.1:4310' }
        );

        expect(tools).toEqual(['workspace_notes_read', 'workspace_notes_update']);
    });

    it('blocks generated AGENTS.md writes', () => {
        expect(
            targetsGeneratedInstructionFile(
                {
                    params: { file_path: '/tmp/workspace/AGENTS.md' },
                    toolName: 'write_file',
                },
                {
                    workspaceDir: '/tmp/workspace',
                }
            )
        ).toBe(true);
        expect(
            targetsGeneratedInstructionFile(
                {
                    derivedPaths: ['/tmp/workspace/AGENTS.md'],
                    params: {},
                    toolName: 'apply_patch',
                },
                {
                    workspaceDir: '/tmp/workspace',
                }
            )
        ).toBe(true);
        expect(
            targetsGeneratedInstructionFile(
                {
                    params: { cmd: 'printf nope > AGENTS.md', cwd: '/tmp/workspace' },
                    toolName: 'exec',
                },
                {
                    workspaceDir: '/tmp/workspace',
                }
            )
        ).toBe(true);
        expect(
            targetsGeneratedInstructionFile(
                {
                    params: { cmd: 'printf nope > /tmp/workspace/AGENTS.md', cwd: '/tmp/repo' },
                    toolName: 'exec',
                },
                {
                    workspaceDir: '/tmp/workspace',
                }
            )
        ).toBe(true);
    });

    it('blocks writes to marked AGENTS.md files in custom workspaces', () => {
        const workspaceDir = mkdtempSync(path.join(tmpdir(), 'tavern-workspace-guard-'));
        const agentsPath = path.join(workspaceDir, 'AGENTS.md');

        try {
            writeFileSync(
                agentsPath,
                'This AGENTS.md file is generated by Tavern. Use workspace notes tools.\n'
            );

            expect(
                targetsGeneratedInstructionFile(
                    {
                        params: { file_path: agentsPath },
                        toolName: 'write_file',
                    },
                    {
                        workspaceDir: '/tmp/default-workspace',
                    }
                )
            ).toBe(true);
            expect(
                targetsGeneratedInstructionFile(
                    {
                        params: { cmd: `printf nope > ${agentsPath}`, cwd: '/tmp/repo' },
                        toolName: 'exec',
                    },
                    {
                        workspaceDir: '/tmp/default-workspace',
                    }
                )
            ).toBe(true);
        } finally {
            rmSync(workspaceDir, { force: true, recursive: true });
        }
    });

    it('allows unrelated writes', () => {
        expect(
            targetsGeneratedInstructionFile(
                {
                    params: { file_path: '/tmp/workspace/README.md' },
                    toolName: 'write_file',
                },
                {
                    workspaceDir: '/tmp/workspace',
                }
            )
        ).toBe(false);
        expect(
            targetsGeneratedInstructionFile(
                {
                    params: { file_path: '/tmp/repo/AGENTS.md' },
                    toolName: 'write_file',
                },
                {
                    workspaceDir: '/tmp/workspace',
                }
            )
        ).toBe(false);
        expect(
            targetsGeneratedInstructionFile(
                {
                    params: { cmd: 'printf ok > AGENTS.md', cwd: '/tmp/repo' },
                    toolName: 'exec',
                },
                {
                    workspaceDir: '/tmp/workspace',
                }
            )
        ).toBe(false);
        expect(
            targetsGeneratedInstructionFile(
                {
                    params: { cmd: 'cat AGENTS.md', cwd: '/tmp/workspace' },
                    toolName: 'exec',
                },
                {
                    workspaceDir: '/tmp/workspace',
                }
            )
        ).toBe(false);
    });
});

function readManifestToolNames() {
    const dirname = path.dirname(fileURLToPath(import.meta.url));
    const manifestPath = path.join(dirname, '..', 'openclaw.plugin.json');
    return JSON.parse(readFileSync(manifestPath, 'utf8')).contracts.tools;
}
