import fs from 'node:fs/promises';
import path from 'node:path';
import type { AgentRuntimeAgent } from '@tavern/api';
import { AGENT_HOME, AGENT_WORKSPACE } from '../config.ts';
import type { Database } from '../db/sqlite.ts';
import {
    generateAgentInstructions,
    generatedInstructionFileName,
    getAgentWorkspaceSource,
    registerAgentWorkspace,
} from '../workspace/instructions.ts';
import { seedTavernAgentSkill } from './skill-library.ts';

export const agentEngineAgentId = 'main';

const soulFileName = 'SOUL.md';
const defaultSoul = `# SOUL.md

You are the resident Tavern agent.

Be direct, pragmatic, and useful. Keep the user's momentum. Prefer concrete action over vague narration.
`;

export async function prepareAgentEngineInstructions(
    db: Database,
    agent: AgentRuntimeAgent | string = agentEngineAgentId
) {
    const agentId = typeof agent === 'string' ? agent : agent.id;
    const agentName = typeof agent === 'string' ? 'Tavern' : agent.name;
    const workspaceDir = typeof agent === 'string' ? AGENT_WORKSPACE : agent.workspaceFolder;
    const source =
        getAgentWorkspaceSource(db, agentId) ??
        registerAgentWorkspace(db, {
            agentId,
            agentName,
            workspaceDir,
        });
    const generated = await generateAgentInstructions(db, source.agentId);
    const soul = await readOrSeedSoul();
    const instructions = composeAgentEngineInstructions({
        agentInstructions: generated.content,
        soul,
    });

    await seedTavernAgentSkill();

    return {
        content: instructions,
        path: path.join(source.workspaceDir, generatedInstructionFileName),
        source,
    };
}

async function readOrSeedSoul() {
    const soulPath = path.join(AGENT_HOME, soulFileName);
    const existing = await fs.readFile(soulPath, 'utf8').catch(() => null);

    if (existing !== null) {
        return existing;
    }

    await fs.mkdir(path.dirname(soulPath), { recursive: true });
    await fs.writeFile(soulPath, defaultSoul, { mode: 0o600 });
    return defaultSoul;
}

function composeAgentEngineInstructions(input: { agentInstructions: string; soul: string }) {
    return [
        '<!-- GENERATED BY TAVERN. The local agent loads this file as the instructions prompt. -->',
        input.agentInstructions.trim(),
        '## SOUL',
        input.soul.trim(),
    ].join('\n\n');
}
