/**
 * Seeded design skill for everything agents render: inline visuals, widget
 * fences, and artifact pages. The skill sources are real files beside this
 * module (visuals-skill/) so the design-tuning loop edits markdown, not
 * template literals; bun inlines them at build time. Icons are generated by
 * scripts/generate-visuals-skill-icons.mjs from the app's HugeIcons set.
 *
 * The Chart.js CDN pin taught in design-system.md must match the CSP in the
 * app's visual renderer (apps/website/src/widgets/visual.tsx); update both
 * together.
 */

import designSystemMd from './visuals-skill/design-system.md' with { type: 'text' };
import iconsMd from './visuals-skill/icons.md' with { type: 'text' };
import { visualsSkillIconFiles, visualsSkillIconManifest } from './visuals-skill/icons.ts';
import skillMd from './visuals-skill/SKILL.md' with { type: 'text' };

export const visualsSkillId = 'visuals';

export const defaultVisualsSkill: string = skillMd;

/** Reference and asset files seeded beside SKILL.md, keyed by relative path. */
export const visualsSkillFiles: Record<string, string> = {
    'references/design-system.md': designSystemMd,
    'references/icons.md': iconsMd,
    'references/icons/manifest.json': `${JSON.stringify({ icons: visualsSkillIconManifest }, null, 2)}\n`,
    ...Object.fromEntries(
        Object.entries(visualsSkillIconFiles).map(([file, svg]) => [`assets/icons/${file}`, svg])
    ),
};
