import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import {
    type AgentRuntimeAgent,
    agentRuntimeMutationHeaders,
    agentRuntimeMutationOrigins,
} from '@tavern/api';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { closeDb, getDb, initTestDb } from '../db/connection.ts';
import { ensureRuntimeSchema } from '../db/schema.ts';
import { handleMemorySettingsRequest } from '../memory/settings.ts';
import type { AgentExecutorInput } from './agent-executor.ts';
import {
    agentSessionInstructionsFresh,
    buildAgentInstructionBundle,
    buildAgentInstructions,
} from './agent-instructions.ts';
import { recordAgentSessionInstructionsHash, startNewAgentSession } from './agent-session-store.ts';
import { getStoredAgent, updateStoredAgent, upsertStoredAgent } from './agents-store.ts';
import { createChat } from './chat-api/index.ts';

const now = '2026-06-29T12:00:00.000Z';

describe('agent instructions', () => {
    let skillsDir: string;
    let workspaceDir: string;

    beforeEach(async () => {
        skillsDir = await mkdtemp(path.join(tmpdir(), 'tavern-agent-skills-'));
        workspaceDir = await mkdtemp(path.join(tmpdir(), 'tavern-agent-workspace-'));
        ensureRuntimeSchema(initTestDb());
    });

    afterEach(async () => {
        closeDb();
        await Promise.all([
            rm(skillsDir, { force: true, recursive: true }),
            rm(workspaceDir, { force: true, recursive: true }),
        ]);
    });

    it('composes SOUL, managed instructions, and NOTES for the AI SDK harness', async () => {
        await writeFile(
            path.join(workspaceDir, 'NOTES.md'),
            '# Agent Notes\n\nPrefer exact source paths.\n'
        );
        await writeFile(
            path.join(workspaceDir, 'SOUL.md'),
            '# SOUL.md\n\nBe terse, concrete, and steady.\n'
        );
        await writeFile(path.join(workspaceDir, 'USER.md'), '# USER.md\n\nUser likes exactness.\n');
        await writeFile(
            path.join(workspaceDir, 'MEMORY.md'),
            '# MEMORY.md\n\nPrefer source-backed answers.\n'
        );

        const instructions = await buildAgentInstructions(
            executorInput({ workspaceFolder: workspaceDir }),
            {
                db: getDb(),
                skillsDir,
            }
        );

        expect(instructions).not.toContain('GENERATED BY TAVERN');
        expect(instructions).toContain('# Tavern Agent Instructions');
        expect(instructions).toContain(
            'You are Tavern, a helpful, proactive, and persistent agent in Tavern'
        );
        expect(instructions).toContain('name the missing Tavern capability plainly');
        expect(instructions).toContain(
            'Do not tell the user to run provider-specific setup commands'
        );
        expect(instructions).toContain('`workbench/` is your working directory');
        expect(instructions).toContain('`workbench/tasks/T-12/`');
        expect(instructions).toContain('## Memory');
        expect(instructions).toContain('`USER.md` and `MEMORY.md` live in your workspace');
        expect(instructions).toContain('## Notes');
        expect(instructions).toContain('Prefer exact source paths.');
        expect(instructions).toContain('## USER');
        expect(instructions).toContain('User likes exactness.');
        expect(instructions).toContain('## MEMORY');
        expect(instructions).toContain('Prefer source-backed answers.');
        expect(instructions).toContain('## SOUL');
        expect(instructions).toContain('comes from `SOUL.md` in your workspace');
        expect(instructions).toContain('edit `SOUL.md` directly');
        expect(instructions).toContain('Be terse, concrete, and steady.');
    });

    it('includes the Tavern chat section with chat id, staleness policy, and tool guidance', async () => {
        const instructions = await buildAgentInstructions(
            executorInput({ workspaceFolder: workspaceDir }),
            { db: getDb(), skillsDir }
        );

        expect(instructions).toContain('This chat:');
        expect(instructions).toContain('- chatId: cht_general');
        expect(instructions).toContain('treat older context and prior data reads as stale');
        expect(instructions).toMatch(/send time in \S+ \(the home timezone\)/);
        expect(instructions).toContain('Chat tools:');
        expect(instructions).toContain('- chat_messages_list:');
        expect(instructions).toContain('Wiki tools (shared durable knowledge)');
    });

    it('teaches NO_REPLY in channels but not in direct messages', async () => {
        createChat({
            id: 'cht_general',
            kind: 'channel',
            participants: [
                { id: 'usr_tavern', kind: 'user', label: 'You', metadata: {} },
                {
                    id: 'agt_primary',
                    kind: 'agent',
                    label: 'Blippy',
                    metadata: { agentId: 'agt_primary' },
                },
            ],
            title: 'general',
        });
        const channelInstructions = await buildAgentInstructions(
            executorInput({ workspaceFolder: workspaceDir }),
            { db: getDb(), skillsDir }
        );
        expect(channelInstructions).toContain('Reply with exactly NO_REPLY');

        createChat({
            id: 'cht_dm',
            kind: 'dm',
            participants: [
                { id: 'usr_tavern', kind: 'user', label: 'You', metadata: {} },
                {
                    id: 'agt_primary',
                    kind: 'agent',
                    label: 'Blippy',
                    metadata: { agentId: 'agt_primary' },
                },
            ],
            title: 'Blippy',
        });
        const dmInput = executorInput({ workspaceFolder: workspaceDir });
        dmInput.chatId = 'cht_dm';
        dmInput.agentSession.chatId = 'cht_dm';
        const dmInstructions = await buildAgentInstructions(dmInput, {
            db: getDb(),
            skillsDir,
        });
        expect(dmInstructions).not.toContain('NO_REPLY');
    });

    it('describes the chat kind and participant roster with the agent marked', async () => {
        createChat({
            id: 'cht_general',
            kind: 'channel',
            participants: [
                { id: 'usr_tavern', kind: 'user', label: 'You', metadata: {} },
                {
                    id: 'agt_primary',
                    kind: 'agent',
                    label: 'Blippy',
                    metadata: { agentId: 'agt_primary' },
                },
                {
                    id: 'agt_tiny',
                    kind: 'agent',
                    label: 'Tiny',
                    metadata: { agentId: 'agt_tiny' },
                },
            ],
            title: 'general',
        });

        const instructions = await buildAgentInstructions(
            executorInput({ workspaceFolder: workspaceDir }),
            { db: getDb(), skillsDir }
        );

        expect(instructions).toContain('This is the "general" channel.');
        expect(instructions).toContain(
            '- Participants:\n  - Blippy (you)\n  - Tiny (agent)\n  - You'
        );
    });

    it('shows each agent seat with its bio so agents know who does what', async () => {
        upsertStoredAgent({
            agent: {
                bio: 'Runs the Amazon Merch business.',
                enabledSkillIds: [],
                id: 'agt_tiny',
                isAdmin: false,
                name: 'Tiny',
                primaryColor: null,
                workspaceFolder: '.tavern/agents/agt_tiny/workspace',
            },
        });
        createChat({
            id: 'cht_general',
            kind: 'channel',
            participants: [
                { id: 'usr_tavern', kind: 'user', label: 'You', metadata: {} },
                {
                    id: 'agt_primary',
                    kind: 'agent',
                    label: 'Blippy',
                    metadata: { agentId: 'agt_primary' },
                },
                {
                    id: 'agt_tiny',
                    kind: 'agent',
                    label: 'Tiny',
                    metadata: { agentId: 'agt_tiny' },
                },
            ],
            title: 'general',
        });

        const instructions = await buildAgentInstructions(
            executorInput({ bio: 'Keeps the household running.', workspaceFolder: workspaceDir }),
            { db: getDb(), skillsDir }
        );

        expect(instructions).toContain('- Blippy (you) — Keeps the household running.');
        expect(instructions).toContain('- Tiny (agent) — Runs the Amazon Merch business.');
    });

    it('keeps the instructions fingerprint stable across core memory edits', async () => {
        await writeFile(path.join(workspaceDir, 'MEMORY.md'), '# MEMORY.md\n\nFirst.\n');
        const first = await buildAgentInstructionBundle(
            executorInput({ workspaceFolder: workspaceDir }),
            { db: getDb(), skillsDir }
        );

        await writeFile(
            path.join(workspaceDir, 'MEMORY.md'),
            '# MEMORY.md\n\nRewritten by extraction.\n'
        );
        const afterMemoryEdit = await buildAgentInstructionBundle(
            executorInput({ workspaceFolder: workspaceDir }),
            { db: getDb(), skillsDir }
        );
        expect(afterMemoryEdit.instructions).toContain('Rewritten by extraction.');
        expect(afterMemoryEdit.fingerprint).toBe(first.fingerprint);

        await writeFile(path.join(workspaceDir, 'SOUL.md'), '# SOUL.md\n\nA new identity.\n');
        const afterSoulEdit = await buildAgentInstructionBundle(
            executorInput({ workspaceFolder: workspaceDir }),
            { db: getDb(), skillsDir }
        );
        expect(afterSoulEdit.fingerprint).not.toBe(first.fingerprint);
    });

    it('reports session instructions freshness against the live compose', async () => {
        upsertStoredAgent({
            agent: {
                enabledSkillIds: [],
                id: 'agt_primary',
                isAdmin: true,
                name: 'Tavern',
                primaryColor: null,
                workspaceFolder: workspaceDir,
            },
        });
        createChat({
            id: 'cht_general',
            kind: 'channel',
            participants: [
                { id: 'usr_tavern', kind: 'user', label: 'You', metadata: {} },
                {
                    id: 'agt_primary',
                    kind: 'agent',
                    label: 'Tavern',
                    metadata: { agentId: 'agt_primary' },
                },
            ],
            title: 'general',
        });
        const session = startNewAgentSession({
            agentParticipantId: 'agt_primary',
            chatId: 'cht_general',
        });

        // No instructions delivered yet: fresh by construction.
        expect(await agentSessionInstructionsFresh(session)).toBeNull();

        const agent = getStoredAgent('agt_primary');
        if (!agent) {
            throw new Error('Agent was not stored.');
        }
        const bundle = await buildAgentInstructionBundle(
            { agent, agentSession: session, chatId: 'cht_general' },
            { seedSkills: false }
        );
        recordAgentSessionInstructionsHash({ hash: bundle.fingerprint, id: session.id });
        expect(await agentSessionInstructionsFresh(session)).toBe(true);

        updateStoredAgent({ agentId: 'agt_primary', bio: 'Runs the Amazon Merch business.' });
        expect(await agentSessionInstructionsFresh(session)).toBe(false);
    });

    it('keeps Wiki tool guidance when core Memory is disabled', async () => {
        await handleMemorySettingsRequest(
            new Request('http://runtime.test/memory/settings', {
                body: JSON.stringify({ enabled: false }),
                headers: {
                    'content-type': 'application/json',
                    [agentRuntimeMutationHeaders.origin]: agentRuntimeMutationOrigins.tavern,
                },
                method: 'PUT',
            })
        );

        const instructions = await buildAgentInstructions(
            executorInput({ workspaceFolder: workspaceDir }),
            { db: getDb(), skillsDir }
        );

        expect(instructions).toContain('Chat tools:');
        expect(instructions).toContain('Wiki tools (shared durable knowledge)');
        expect(instructions).toContain('wiki_search');
    });

    it('nudges agents to capture and maintain skills', async () => {
        const instructions = await buildAgentInstructions(
            executorInput({ workspaceFolder: workspaceDir }),
            { db: getDb(), skillsDir }
        );

        expect(instructions).toContain('save the approach as a skill');
        expect(instructions).toContain('patch it immediately');
    });

    it('adds tool-use enforcement and execution discipline for gpt-family models', async () => {
        const instructions = await buildAgentInstructions(
            executorInput({ workspaceFolder: workspaceDir }, 'gpt-5.5'),
            { db: getDb(), skillsDir }
        );

        expect(instructions).toContain('## Tool-Use Enforcement');
        expect(instructions).toContain('## Execution Discipline');
        expect(instructions).not.toContain('## Operational Directives');
    });

    it('adds Google operational directives for gemini models', async () => {
        const instructions = await buildAgentInstructions(
            executorInput({ workspaceFolder: workspaceDir }, 'gemini-2.5-pro'),
            { db: getDb(), skillsDir }
        );

        expect(instructions).toContain('## Tool-Use Enforcement');
        expect(instructions).toContain('## Operational Directives');
        expect(instructions).not.toContain('## Execution Discipline');
    });

    it('adds no model steering for claude models', async () => {
        const instructions = await buildAgentInstructions(
            executorInput({ workspaceFolder: workspaceDir }, 'claude-opus-4-8'),
            { db: getDb(), skillsDir }
        );

        expect(instructions).not.toContain('## Tool-Use Enforcement');
        expect(instructions).not.toContain('## Execution Discipline');
    });

    it('keeps assigned skills out of the AI SDK instruction text', async () => {
        const instructions = await buildAgentInstructions(
            executorInput({
                enabledSkillIds: ['research'],
                workspaceFolder: workspaceDir,
            }),
            { db: getDb(), seedSkills: false }
        );

        expect(instructions).toContain('You are Tavern');
        expect(instructions).not.toContain('## Skill: research');
        expect(instructions).not.toContain('SKILL.md');
    });

    it('keeps core memory files out of the system prompt when Memory is disabled', async () => {
        await writeFile(path.join(workspaceDir, 'USER.md'), '# USER.md\n\nHidden while off.\n');
        await writeFile(path.join(workspaceDir, 'MEMORY.md'), '# MEMORY.md\n\nHidden while off.\n');
        await handleMemorySettingsRequest(
            new Request('http://runtime.test/memory/settings', {
                body: JSON.stringify({ enabled: false }),
                headers: {
                    'content-type': 'application/json',
                    [agentRuntimeMutationHeaders.origin]: agentRuntimeMutationOrigins.tavern,
                },
                method: 'PUT',
            })
        );

        const instructions = await buildAgentInstructions(
            executorInput({ workspaceFolder: workspaceDir }),
            { db: getDb(), skillsDir }
        );

        expect(instructions).toContain('Memory is currently disabled');
        expect(instructions).not.toContain('Hidden while off.');
        expect(instructions).not.toContain('## USER');
        expect(instructions).not.toContain('## MEMORY');
    });
});

function executorInput(
    agentOverrides: Partial<AgentRuntimeAgent> = {},
    model = 'gpt-4.1-mini'
): AgentExecutorInput {
    return {
        agent: {
            enabledSkillIds: [],
            id: 'agt_primary',
            isAdmin: true,
            name: 'Tavern',
            primaryColor: null,
            workspaceFolder: '.tavern/agents/agt_primary/workspace',
            ...agentOverrides,
        } satisfies AgentRuntimeAgent,
        agentSession: {
            agentId: 'agt_primary',
            agentParticipantId: 'agt_primary',
            archivedAt: null,
            chatId: 'cht_general',
            createdAt: now,
            effectiveModel: { model, provider: 'openai' },
            generation: 1,
            id: 'ags_cht_general_agt_primary_1',
            promptContextSequence: 0,
            resumeState: null,
            runtimeSessionId: null,
            status: 'active',
            updatedAt: now,
        },
        attachments: [],
        chatId: 'cht_general',
        content: 'hello',
        requestMessageId: 'msg_1',
        responseId: 'rsp_run_1',
        runId: 'run_1',
    };
}
