import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import {
    type AgentRuntimeAgent,
    agentRuntimeMutationHeaders,
    agentRuntimeMutationOrigins,
} from '@tavern/api';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { closeDb, getDb, initTestDb } from '../db/connection.ts';
import { ensureRuntimeSchema } from '../db/schema.ts';
import { handleMemorySettingsRequest } from '../memory/settings.ts';
import type { AgentExecutorInput } from './agent-executor.ts';
import {
    agentSessionInstructionsFresh,
    buildAgentInstructionBundle,
    buildAgentInstructions,
} from './agent-instructions.ts';
import { recordAgentSessionInstructionsHash, startNewAgentSession } from './agent-session-store.ts';
import { getStoredAgent, updateStoredAgent, upsertStoredAgent } from './agents-store.ts';
import { createChat } from './chat-api/index.ts';

const now = '2026-06-29T12:00:00.000Z';

describe('agent instructions', () => {
    let skillsDir: string;
    let workspaceDir: string;

    beforeEach(async () => {
        skillsDir = await mkdtemp(path.join(tmpdir(), 'tavern-agent-skills-'));
        workspaceDir = await mkdtemp(path.join(tmpdir(), 'tavern-agent-workspace-'));
        ensureRuntimeSchema(initTestDb());
    });

    afterEach(async () => {
        closeDb();
        await Promise.all([
            rm(skillsDir, { force: true, recursive: true }),
            rm(workspaceDir, { force: true, recursive: true }),
        ]);
    });

    it('composes SOUL, managed instructions, and NOTES for the AI SDK harness', async () => {
        await writeFile(
            path.join(workspaceDir, 'NOTES.md'),
            '# Agent Notes\n\nPrefer exact source paths.\n'
        );
        await writeFile(
            path.join(workspaceDir, 'SOUL.md'),
            '# SOUL.md\n\nBe terse, concrete, and steady.\n'
        );
        await writeFile(path.join(workspaceDir, 'USER.md'), '# USER.md\n\nUser likes exactness.\n');
        await writeFile(
            path.join(workspaceDir, 'MEMORY.md'),
            '# MEMORY.md\n\nPrefer source-backed answers.\n'
        );

        const instructions = await buildAgentInstructions(
            executorInput({ workspaceFolder: workspaceDir }),
            {
                db: getDb(),
                skillsDir,
            }
        );

        expect(instructions).not.toContain('GENERATED BY TAVERN');
        expect(instructions).toContain('# Grotto Agent Instructions');
        expect(instructions).toContain(
            'You are Tavern, a helpful, proactive, and persistent agent in Grotto'
        );
        expect(instructions).toContain('name the missing Grotto capability plainly');
        expect(instructions).toContain(
            'Do not tell the user to run provider-specific setup commands'
        );
        expect(instructions).toContain('`workbench/` is your working directory');
        expect(instructions).toContain('`workbench/tasks/T-12/`');
        expect(instructions).toContain('## Memory');
        expect(instructions).toContain('`USER.md` and `MEMORY.md` live in your workspace');
        expect(instructions).toContain('## Notes');
        expect(instructions).toContain('Prefer exact source paths.');
        expect(instructions).toContain('## USER');
        expect(instructions).toContain('User likes exactness.');
        expect(instructions).toContain('## MEMORY');
        expect(instructions).toContain('Prefer source-backed answers.');
        expect(instructions).toContain('## SOUL');
        expect(instructions).toContain('comes from `SOUL.md` in your workspace');
        expect(instructions).toContain('edit `SOUL.md` directly');
        expect(instructions).toContain('Be terse, concrete, and steady.');
    });

    it('includes the chats section with staleness policy and recall hygiene', async () => {
        const instructions = await buildAgentInstructions(
            executorInput({ workspaceFolder: workspaceDir }),
            { db: getDb(), skillsDir }
        );

        expect(instructions).toContain('Your chats:');
        expect(instructions).toContain('one conversation spans them all: this session');
        expect(instructions).toContain('treat older context and prior data reads as stale');
        expect(instructions).toMatch(/send time in \S+ \(the home timezone\)/);
        expect(instructions).toContain('Recalled Wiki blocks are automatic background context');
        // Chat identity and rosters are per-turn prompt content, never here.
        expect(instructions).not.toContain('chatId: cht_general');
    });

    it('teaches NO_REPLY, mention expectation, etiquette, and DM discretion unconditionally', async () => {
        const instructions = await buildAgentInstructions(
            executorInput({ workspaceFolder: workspaceDir }),
            { db: getDb(), skillsDir }
        );

        expect(instructions).toContain('Reply with exactly NO_REPLY');
        expect(instructions).toContain(
            'A mention of you means you specifically are expected to act or answer.'
        );
        expect(instructions).toContain("never echo a peer's answer");
        expect(instructions).toContain(
            'What someone shares in a DM was shared with you, not with every room.'
        );
    });

    it('reports session instructions freshness against the live compose', async () => {
        upsertStoredAgent({
            agent: {
                enabledSkillIds: [],
                id: 'agt_primary',
                isAdmin: true,
                name: 'Tavern',
                primaryColor: null,
                workspaceFolder: workspaceDir,
            },
        });
        createChat({
            id: 'cht_general',
            kind: 'channel',
            participants: [
                { id: 'usr_tavern', kind: 'user', label: 'You', metadata: {} },
                {
                    id: 'agt_primary',
                    kind: 'agent',
                    label: 'Tavern',
                    metadata: { agentId: 'agt_primary' },
                },
            ],
            title: 'general',
        });
        const session = startNewAgentSession({ agentId: 'agt_primary' });

        // No instructions delivered yet: fresh by construction.
        expect(await agentSessionInstructionsFresh(session)).toBeNull();

        const agent = getStoredAgent('agt_primary');
        if (!agent) {
            throw new Error('Agent was not stored.');
        }
        const bundle = await buildAgentInstructionBundle(
            { agent, agentSession: session },
            { seedSkills: false }
        );
        recordAgentSessionInstructionsHash({ hash: bundle.fingerprint, id: session.id });
        expect(await agentSessionInstructionsFresh(session)).toBe(true);

        updateStoredAgent({ agentId: 'agt_primary', webAccessEnabled: true });
        expect(await agentSessionInstructionsFresh(session)).toBe(false);
    });

    it('keeps Wiki tool guidance when core Memory is disabled', async () => {
        await handleMemorySettingsRequest(
            new Request('http://runtime.test/memory/settings', {
                body: JSON.stringify({ enabled: false }),
                headers: {
                    'content-type': 'application/json',
                    [agentRuntimeMutationHeaders.origin]: agentRuntimeMutationOrigins.tavern,
                },
                method: 'PUT',
            })
        );

        const instructions = await buildAgentInstructions(
            executorInput({ workspaceFolder: workspaceDir }),
            { db: getDb(), skillsDir }
        );

        expect(instructions).toContain('The shared Wiki remains available through Wiki tools');
        expect(instructions).toContain('run `wiki_search` before concluding you lack context');
    });

    it('nudges agents to capture and maintain skills', async () => {
        const instructions = await buildAgentInstructions(
            executorInput({ workspaceFolder: workspaceDir }),
            { db: getDb(), skillsDir }
        );

        expect(instructions).toContain('save the approach as a skill');
        expect(instructions).toContain('patch it immediately');
    });

    it('adds tool-use enforcement and execution discipline for gpt-family models', async () => {
        const instructions = await buildAgentInstructions(
            executorInput({ workspaceFolder: workspaceDir }, 'gpt-5.5'),
            { db: getDb(), skillsDir }
        );

        expect(instructions).toContain('## Tool-Use Enforcement');
        expect(instructions).toContain('## Execution Discipline');
        expect(instructions).not.toContain('## Operational Directives');
    });

    it('adds Google operational directives for gemini models', async () => {
        const instructions = await buildAgentInstructions(
            executorInput({ workspaceFolder: workspaceDir }, 'gemini-2.5-pro'),
            { db: getDb(), skillsDir }
        );

        expect(instructions).toContain('## Tool-Use Enforcement');
        expect(instructions).toContain('## Operational Directives');
        expect(instructions).not.toContain('## Execution Discipline');
    });

    it('adds no model steering for claude models', async () => {
        const instructions = await buildAgentInstructions(
            executorInput({ workspaceFolder: workspaceDir }, 'claude-opus-4-8'),
            { db: getDb(), skillsDir }
        );

        expect(instructions).not.toContain('## Tool-Use Enforcement');
        expect(instructions).not.toContain('## Execution Discipline');
    });

    it('keeps assigned skills out of the AI SDK instruction text', async () => {
        const instructions = await buildAgentInstructions(
            executorInput({
                enabledSkillIds: ['research'],
                workspaceFolder: workspaceDir,
            }),
            { db: getDb(), seedSkills: false }
        );

        expect(instructions).toContain('You are Tavern');
        expect(instructions).not.toContain('## Skill: research');
        expect(instructions).not.toContain('SKILL.md');
    });

    it('keeps core memory files out of the system prompt when Memory is disabled', async () => {
        await writeFile(path.join(workspaceDir, 'USER.md'), '# USER.md\n\nHidden while off.\n');
        await writeFile(path.join(workspaceDir, 'MEMORY.md'), '# MEMORY.md\n\nHidden while off.\n');
        await handleMemorySettingsRequest(
            new Request('http://runtime.test/memory/settings', {
                body: JSON.stringify({ enabled: false }),
                headers: {
                    'content-type': 'application/json',
                    [agentRuntimeMutationHeaders.origin]: agentRuntimeMutationOrigins.tavern,
                },
                method: 'PUT',
            })
        );

        const instructions = await buildAgentInstructions(
            executorInput({ workspaceFolder: workspaceDir }),
            { db: getDb(), skillsDir }
        );

        expect(instructions).toContain('Memory is currently disabled');
        expect(instructions).not.toContain('Hidden while off.');
        expect(instructions).not.toContain('## USER');
        expect(instructions).not.toContain('## MEMORY');
    });
});

function executorInput(
    agentOverrides: Partial<AgentRuntimeAgent> = {},
    model = 'gpt-4.1-mini'
): AgentExecutorInput {
    return {
        agent: {
            enabledSkillIds: [],
            id: 'agt_primary',
            isAdmin: true,
            name: 'Tavern',
            primaryColor: null,
            workspaceFolder: '.tavern/agents/agt_primary/workspace',
            ...agentOverrides,
        } satisfies AgentRuntimeAgent,
        agentParticipantId: 'agt_primary',
        agentSession: {
            agentId: 'agt_primary',
            archivedAt: null,
            createdAt: now,
            effectiveModel: { model, provider: 'openai' },
            generation: 1,
            id: 'ags_agt_primary_1',
            lastTurnAt: null,
            resumeState: null,
            runtimeSessionId: null,
            status: 'active',
            updatedAt: now,
        },
        attachments: [],
        chatId: 'cht_general',
        content: 'hello',
        requestMessageId: 'msg_1',
        responseId: 'rsp_run_1',
        runId: 'run_1',
    };
}
