export const developmentChatDemoIds = {
    activityTurn: 'cht_demo_activity_turn',
    approvalFlow: 'cht_demo_approval_flow',
    attachment: 'cht_demo_attachment',
    calendarDay: 'cht_demo_calendar_day',
    calendarEvent: 'cht_demo_calendar_event',
    charts: 'cht_demo_charts',
    composedChart: 'cht_demo_composed_chart',
    lineChart: 'cht_demo_line_chart',
    longContent: 'cht_demo_long_content',
    merchbaseSalesChart: 'cht_demo_merchbase_sales_chart',
    richResponseCatalog: 'cht_demo_rich_response_catalog',
    streamingStack: 'cht_demo_streaming_stack',
    toolHeaders: 'cht_demo_tool_headers',
} as const;
