import type { components, operations, paths } from './generated/openapi.d.ts';

export type { components, operations, paths, webhooks } from './generated/openapi.d.ts';

export type TavernApiComponents = components;
export type TavernApiPaths = paths;
export type TavernApiOperations = operations;

export type TavernApiSchema<Name extends keyof components['schemas']> = components['schemas'][Name];

export type TavernArtifact = TavernApiSchema<'ChatArtifact'>;
export type TavernAgentApiError = TavernApiSchema<'AgentApiError'>;
export type TavernAgentChannel = TavernApiSchema<'AgentChannel'>;
export type TavernAgentChannelMember = TavernApiSchema<'AgentChannelMember'>;
export type TavernAgentChannelMembers = TavernApiSchema<'AgentChannelMembers'>;
export type TavernAgentHistoryResponse = TavernApiSchema<'AgentHistoryResponse'>;
export type TavernAgentMessage = TavernApiSchema<'AgentMessage'>;
export type TavernAgentSearchResult = TavernApiSchema<'AgentSearchResult'>;
export type TavernAgentSearchResultList = TavernApiSchema<'AgentSearchResultList'>;
export type TavernAgentSendApiError = TavernApiSchema<'AgentSendApiError'>;
export type TavernAgentSendRequest = TavernApiSchema<'AgentSendRequest'>;
export type TavernAgentSendResponse = TavernApiSchema<'AgentSendResponse'>;
export type TavernAgentServerInfo = TavernApiSchema<'AgentServerInfo'>;
export type TavernChat = TavernApiSchema<'Chat'>;
export type TavernChatEvent = TavernApiSchema<'ChatEvent'>;
export type TavernChatMessage = TavernApiSchema<'ChatMessage'>;
export type TavernChatMessageReceipt = TavernApiSchema<'ChatMessageReceipt'>;
export type TavernChatResponse = TavernApiSchema<'ChatResponse'>;
export type TavernChatTimelinePage = TavernApiSchema<'ChatTimelinePage'>;
export type TavernClearChatReceipt = TavernApiSchema<'ClearChatReceipt'>;
export type TavernCreateChatRequest = TavernApiSchema<'CreateChatRequest'>;
export type TavernCreateDeliveryRequest = TavernApiSchema<'CreateDeliveryRequest'>;
export type TavernCreateMessageRequest = TavernApiSchema<'CreateMessageRequest'>;
export type TavernDeleteResponseReceipt = TavernApiSchema<'DeleteResponseReceipt'>;
export type TavernEventList = TavernApiSchema<'EventList'>;
export type TavernListChatsResponse = TavernApiSchema<'ListChatsResponse'>;
export type TavernListMessagesResponse = TavernApiSchema<'ListMessagesResponse'>;
export type TavernListResponsesResponse = TavernApiSchema<'ListResponsesResponse'>;
export type TavernMarkReadRequest = TavernApiSchema<'MarkReadRequest'>;
export type TavernResponseActivity = TavernApiSchema<'ResponseActivity'>;
export type TavernResponseEvidence = TavernApiSchema<'ResponseEvidence'>;
export type TavernTurnPromptEvidence = TavernApiSchema<'TurnPromptEvidence'>;
export type TavernTurnFileChange = TavernApiSchema<'TurnFileChange'>;
export type TavernTurnFileChangeEvidence = TavernApiSchema<'TurnFileChangeEvidence'>;
export type TavernTurnPromptRecallHit = TavernApiSchema<'TurnPromptRecallHit'>;
export type TavernUpsertArtifactRequest = TavernApiSchema<'UpsertArtifactRequest'>;
export type TavernUpsertResponseActivityRequest = TavernApiSchema<'UpsertResponseActivityRequest'>;
export type TavernUpsertResponseRequest = TavernApiSchema<'UpsertResponseRequest'>;

export * from './agent-appearance.js';
export * from './development-chat-demos.js';
export * from './plugins/index.js';
export * from './rich-references.js';
export * from './runtime/contracts.js';
export * from './runtime/dev-toolkit.js';
export * from './runtime/identity.js';
export * from './runtime/mcp.js';
export * from './runtime/model-identity.js';
export * from './runtime/model-providers.js';
export * from './runtime/pane-links.js';
export * from './runtime/routes.js';
export * from './runtime/runtime-aliases.js';
export * from './runtime/skill-hub.js';
export * from './runtime/skills.js';
export * from './runtime/tool-setup.js';
export * from './widgets/calendar/contracts.js';
export * from './widgets/charts/contracts.js';
export * from './widgets/contracts.js';
export * from './widgets/document/contracts.js';
export * from './widgets/merchbase/contracts.js';
export * from './widgets/prompt.js';
