export const pinnedTabColorOptions = [
    { id: 'slate', label: 'Slate', value: '#64748b' },
    { id: 'red', label: 'Red', value: '#ef4444' },
    { id: 'orange', label: 'Orange', value: '#f97316' },
    { id: 'amber', label: 'Amber', value: '#f59e0b' },
    { id: 'yellow', label: 'Yellow', value: '#eab308' },
    { id: 'lime', label: 'Lime', value: '#84cc16' },
    { id: 'green', label: 'Green', value: '#22c55e' },
    { id: 'emerald', label: 'Emerald', value: '#10b981' },
    { id: 'teal', label: 'Teal', value: '#14b8a6' },
    { id: 'cyan', label: 'Cyan', value: '#06b6d4' },
    { id: 'sky', label: 'Sky', value: '#0ea5e9' },
    { id: 'blue', label: 'Blue', value: '#3b82f6' },
    { id: 'indigo', label: 'Indigo', value: '#6366f1' },
    { id: 'violet', label: 'Violet', value: '#8b5cf6' },
    { id: 'purple', label: 'Purple', value: '#a855f7' },
    { id: 'fuchsia', label: 'Fuchsia', value: '#d946ef' },
    { id: 'pink', label: 'Pink', value: '#ec4899' },
    { id: 'rose', label: 'Rose', value: '#f43f5e' },
] as const;
