/**
 * Build the widget:page iframe runtime from the kit sources (one source of
 * truth — never fork the kit). Emits src/widgets/page-runtime/generated/
 * page-runtime.ts, a plain module exporting the bundled runtime script and
 * compiled stylesheet as strings so vite, tsc, and bun test all load it with
 * no extra plumbing. Run via `bun run sync:page-runtime`; dev/build/test/
 * typecheck chain it automatically.
 *
 * - Script: esbuild bundles entry.tsx (React + kit + sucrase compiler) into
 *   one IIFE injected into the iframe srcDoc.
 * - Styles: Tailwind v4 compiles page-runtime.css — tokens.css plus the
 *   utilities scanned from the kit dependency graph — and the Geist faces the
 *   kit typography uses are inlined as data: URLs (an opaque-origin srcDoc
 *   cannot fetch app assets).
 */
import { mkdir } from 'node:fs/promises';
import path from 'node:path';
import { compile } from '@tailwindcss/node';
import { Scanner } from '@tailwindcss/oxide';
import { build } from 'esbuild';

const websiteRoot = path.resolve(import.meta.dir, '..');
const stylesDir = path.join(websiteRoot, 'src/styles');
const generatedDir = path.join(websiteRoot, 'src/widgets/page-runtime/generated');

const bundle = await build({
    absWorkingDir: websiteRoot,
    bundle: true,
    define: { 'process.env.NODE_ENV': '"production"' },
    entryPoints: [path.join(websiteRoot, 'src/widgets/page-runtime/entry.tsx')],
    format: 'iife',
    jsx: 'automatic',
    minify: true,
    outdir: generatedDir,
    platform: 'browser',
    target: 'es2020',
    write: false,
});

const runtimeJs = outputText(bundle.outputFiles, '.js');
const importedCss = outputText(bundle.outputFiles, '.css');

const inputPath = path.join(stylesDir, 'page-runtime.css');
const compiler = await compile(await Bun.file(inputPath).text(), {
    base: stylesDir,
    onDependency: () => {},
});
const candidates = new Scanner({ sources: compiler.sources }).scan();
const tailwindCss = compiler.build(candidates);

const runtimeCss = [await geistFontFaces(), tailwindCss, importedCss]
    .filter((part) => part.length > 0)
    .join('\n');

await mkdir(generatedDir, { recursive: true });
await Bun.write(
    path.join(generatedDir, 'page-runtime.ts'),
    [
        '// Generated by scripts/build-page-runtime.ts — do not edit.',
        `export const pageRuntimeJs = ${JSON.stringify(runtimeJs)};`,
        `export const pageRuntimeCss = ${JSON.stringify(runtimeCss)};`,
        '',
    ].join('\n\n')
);

console.log(
    `page-runtime: script ${sizeKb(runtimeJs)} KB, styles ${sizeKb(runtimeCss)} KB -> ${path.relative(websiteRoot, path.join(generatedDir, 'page-runtime.ts'))}`
);

function outputText(files: { path: string; text: string }[], extension: string): string {
    return files
        .filter((file) => file.path.endsWith(extension))
        .map((file) => file.text)
        .join('\n');
}

async function geistFontFaces(): Promise<string> {
    const packagePath = Bun.resolveSync('@fontsource/geist/package.json', websiteRoot);
    const filesDir = path.join(path.dirname(packagePath), 'files');
    const weights = [400, 500, 600];

    const faces = await Promise.all(
        weights.map(async (weight) => {
            const woff2 = await Bun.file(
                path.join(filesDir, `geist-latin-${weight}-normal.woff2`)
            ).bytes();
            const encoded = Buffer.from(woff2).toString('base64');
            return `@font-face{font-family:'Geist';font-style:normal;font-weight:${weight};font-display:swap;src:url(data:font/woff2;base64,${encoded}) format('woff2');}`;
        })
    );

    return faces.join('\n');
}

function sizeKb(text: string): string {
    return (new TextEncoder().encode(text).byteLength / 1024).toFixed(0);
}
