import type { ToolIntentKind } from './chat-transcript-tool-intent-types.ts';

export const commandToolNames = ['bash', 'command', 'exec', 'process', 'shell', 'terminal', 'zsh'];
export const longHeaderSubjectLimit = 72;

// Current managed Hermes built-ins, Tavern first-party tools, and Tavern-owned
// session/tool rows. Unknown plugin or MCP tools still fall through to shape
// inference and then a generic tool summary.
export const mappedToolIntentNames = [
    'approval',
    'bash',
    'browser_back',
    'browser_cdp',
    'browser_click',
    'browser_console',
    'browser_dialog',
    'browser_get_images',
    'browser_navigate',
    'browser_press',
    'browser_scroll',
    'browser_snapshot',
    'browser_type',
    'browser_vision',
    'clarify',
    'computer_use',
    'command',
    'cronjob',
    'delegate_task',
    'discord',
    'discord_admin',
    'edit',
    'exec',
    'execute_code',
    'feishu_doc_read',
    'feishu_drive_add_comment',
    'feishu_drive_list_comment_replies',
    'feishu_drive_list_comments',
    'feishu_drive_reply_comment',
    'grep',
    'ha_call_service',
    'ha_get_state',
    'ha_list_entities',
    'ha_list_services',
    'image_generate',
    'kanban_block',
    'kanban_comment',
    'kanban_complete',
    'kanban_create',
    'kanban_heartbeat',
    'kanban_link',
    'kanban_list',
    'kanban_show',
    'kanban_unblock',
    'memory',
    'memory_search',
    'message',
    'mixture_of_agents',
    'patch',
    'process',
    'read',
    'read_file',
    'replace',
    'rg',
    'search',
    'search_files',
    'search_web',
    'send_message',
    'session_search',
    'sessions_history',
    'sessions_list',
    'sessions_read',
    'sessions_send',
    'sessions_spawn',
    'sessions_yield',
    'shell',
    'skill_manage',
    'skill_view',
    'skills_list',
    'terminal',
    'text_to_speech',
    'todo',
    'tool-search',
    'tool_search',
    'tool_search_tool',
    'update_plan',
    'video_analyze',
    'video_generate',
    'vision_analyze',
    'web_extract',
    'web_search',
    'write',
    'write_file',
    'x_search',
    'yb_query_group_info',
    'yb_query_group_members',
    'yb_search_sticker',
    'yb_send_dm',
    'yb_send_sticker',
    'zsh',
] as const;

export const exactToolKinds = {
    approval: 'approval',
    bash: 'command',
    browser_back: 'browser',
    browser_cdp: 'browser',
    browser_click: 'browser',
    browser_console: 'browser',
    browser_dialog: 'browser',
    browser_get_images: 'browser',
    browser_navigate: 'browser',
    browser_press: 'browser',
    browser_scroll: 'browser',
    browser_snapshot: 'browser',
    browser_type: 'browser',
    browser_vision: 'browser',
    clarify: 'clarification',
    computer_use: 'computer',
    command: 'command',
    cronjob: 'automation',
    delegate_task: 'worker',
    discord: 'message',
    discord_admin: 'message',
    edit: 'file-edit',
    exec: 'command',
    execute_code: 'code',
    feishu_doc_read: 'document',
    feishu_drive_add_comment: 'document',
    feishu_drive_list_comment_replies: 'document',
    feishu_drive_list_comments: 'document',
    feishu_drive_reply_comment: 'document',
    grep: 'code-search',
    ha_call_service: 'home',
    ha_get_state: 'home',
    ha_list_entities: 'home',
    ha_list_services: 'home',
    image_generate: 'image',
    kanban_block: 'task',
    kanban_comment: 'task',
    kanban_complete: 'task',
    kanban_create: 'task',
    kanban_heartbeat: 'task',
    kanban_link: 'task',
    kanban_list: 'task',
    kanban_show: 'task',
    kanban_unblock: 'task',
    memory: 'memory',
    memory_search: 'memory',
    message: 'message',
    mixture_of_agents: 'worker',
    patch: 'file-edit',
    process: 'command',
    read: 'file-read',
    read_file: 'file-read',
    replace: 'file-edit',
    rg: 'code-search',
    search: 'code-search',
    search_files: 'code-search',
    search_web: 'web',
    send_message: 'message',
    session_search: 'code-search',
    sessions_history: 'worker',
    sessions_list: 'worker',
    sessions_read: 'worker',
    sessions_send: 'worker',
    sessions_spawn: 'worker',
    sessions_yield: 'worker',
    shell: 'command',
    skill_manage: 'skill',
    skill_view: 'skill',
    skills_list: 'skill',
    terminal: 'command',
    text_to_speech: 'voice',
    todo: 'task',
    'tool-search': 'tool',
    tool_search: 'tool',
    tool_search_tool: 'tool',
    update_plan: 'task',
    video_analyze: 'image',
    video_generate: 'image',
    vision_analyze: 'image',
    web_extract: 'web',
    web_search: 'web',
    write: 'file-edit',
    write_file: 'file-edit',
    x_search: 'web',
    yb_query_group_info: 'message',
    yb_query_group_members: 'message',
    yb_search_sticker: 'message',
    yb_send_dm: 'message',
    yb_send_sticker: 'message',
    zsh: 'command',
} satisfies Record<(typeof mappedToolIntentNames)[number], ToolIntentKind>;

export const exactToolSubjects = {} satisfies Partial<
    Record<(typeof mappedToolIntentNames)[number], string>
>;
