import type { CortexSchemaDefinition } from './contracts.js';

export const defaultCortexPageTypes = [
    'person',
    'company',
    'project',
    'product',
    'brand',
    'campaign',
    'customer-segment',
    'niche',
    'listing',
    'design',
    'collection',
    'marketplace',
    'production-partner',
    'platform',
    'tool',
    'asset',
    'source',
    'content',
    'podcast',
    'x-post',
    'takeaway',
    'investment',
    'trade',
    'thesis',
    'decision',
    'task',
    'reminder',
    'automation',
    'workflow',
    'agent',
    'metric',
    'event',
    'fact',
    'preference',
    'idea',
    'note',
] as const;

export const defaultCortexLinkTypes = [
    'mentions',
    'related_to',
    'depends_on',
    'blocks',
    'supports',
    'contradicts',
    'same_as',
    'uses',
    'owns',
    'targets',
    'tracks',
    'source',
    'sells_on',
    'produced_by',
    'belongs_to',
    'variants_of',
    'targets_niche',
    'inspired_by',
    'derived_from',
    'mentions_ticker',
    'holds',
    'watches',
    'supports_thesis',
    'contradicts_thesis',
    'assigned_to',
    'due_on',
    'automates',
    'configured_by',
    'prefers',
    'created_by',
    'decided_by',
] as const;

export const defaultCortexFrontmatterMappings = [
    { fields: ['mentions'], linkType: 'mentions' },
    { fields: ['platforms', 'tools', 'apis', 'models', 'assets'], linkType: 'uses' },
    { fields: ['uses'], linkType: 'uses' },
    { fields: ['depends_on'], linkType: 'depends_on' },
    { fields: ['blocked_by'], linkType: 'blocks' },
    { fields: ['blocks'], linkType: 'blocks' },
    { fields: ['brand'], linkType: 'owns' },
    { fields: ['owns'], linkType: 'owns' },
    { fields: ['customer_segments', 'audience', 'products'], linkType: 'targets' },
    { fields: ['targets'], linkType: 'targets' },
    { fields: ['marketplace', 'marketplaces', 'channels', 'sells_on'], linkType: 'sells_on' },
    {
        fields: ['production_partner', 'production_partners', 'printed_by', 'produced_by'],
        linkType: 'produced_by',
    },
    { fields: ['niche', 'niches', 'occasion', 'occasions'], linkType: 'targets_niche' },
    { fields: ['collection', 'collections', 'series'], linkType: 'belongs_to' },
    { fields: ['variants', 'variant_of'], linkType: 'variants_of' },
    { fields: ['inspired_by'], linkType: 'inspired_by' },
    { fields: ['metrics'], linkType: 'tracks' },
    { fields: ['tracks'], linkType: 'tracks' },
    { fields: ['related', 'see_also'], linkType: 'related_to' },
    { fields: ['related_to'], linkType: 'related_to' },
    { fields: ['supports'], linkType: 'supports' },
    { fields: ['contradicts'], linkType: 'contradicts' },
    { fields: ['same_as'], linkType: 'same_as' },
    { fields: ['source', 'sources'], linkType: 'source' },
    { fields: ['derived_from'], linkType: 'derived_from' },
    { fields: ['ticker', 'tickers'], linkType: 'mentions_ticker' },
    { fields: ['holdings', 'holds'], linkType: 'holds' },
    { fields: ['watchlist', 'watches'], linkType: 'watches' },
    { fields: ['supports_thesis'], linkType: 'supports_thesis' },
    { fields: ['contradicts_thesis'], linkType: 'contradicts_thesis' },
    { fields: ['assignee', 'assigned_to'], linkType: 'assigned_to' },
    { fields: ['due', 'due_on'], linkType: 'due_on' },
    { fields: ['automates'], linkType: 'automates' },
    { fields: ['configured_by'], linkType: 'configured_by' },
    { fields: ['preferences', 'prefers'], linkType: 'prefers' },
    { fields: ['creator', 'created_by'], linkType: 'created_by' },
    { fields: ['decider', 'decided_by'], linkType: 'decided_by' },
] as const;

export const defaultCortexSchema = {
    frontmatterMappings: defaultCortexFrontmatterMappings.map((mapping) => ({
        fields: [...mapping.fields],
        linkType: mapping.linkType,
    })),
    linkTypes: defaultCortexLinkTypes.map((name) => ({ name })),
    name: 'cortex-base',
    pageTypes: [...defaultCortexPageTypes],
    version: 1,
} satisfies CortexSchemaDefinition;
