export const agentRuntimeMutationHeaders = {
    origin: 'x-tavern-origin',
} as const;

export const agentRuntimeMutationOrigins = {
    tavern: 'tavern',
    agentRuntime: 'agent-runtime',
} as const;

export const agentRuntimeRoutes = {
    agent: (id: string) => `/agents/${id}`,
    agentConfig: (id: string) => `/agents/${id}/config`,
    agentFile: (agentId: string, path: string) =>
        `/agents/${agentId}/files/${encodeURIComponent(path)}`,
    agentBio: (id: string) => `/agents/${id}/bio`,
    agentFiles: (agentId: string) => `/agents/${agentId}/files`,
    agentModel: (id: string) => `/agents/${id}/model`,
    agentName: (id: string) => `/agents/${id}/name`,
    agentPluginGrant: (agentId: string, pluginId: string) =>
        `/agents/${encodeURIComponent(agentId)}/plugins/${encodeURIComponent(pluginId)}/enabled`,
    agentPluginGrants: (id: string) => `/agents/${encodeURIComponent(id)}/plugins`,
    agentThinkingDefault: (id: string) => `/agents/${id}/thinking-default`,
    agentTaskSettings: (id: string) => `/agents/${id}/task-settings`,
    agentWebSettings: (id: string) => `/agents/${id}/web-settings`,
    agents: '/agents',
    capabilities: '/capabilities',
    capability: (id: string) => `/capabilities/${encodeURIComponent(id)}`,
    capabilityRefresh: (id: string) => `/capabilities/${encodeURIComponent(id)}/refresh`,
    capabilitiesRefresh: '/capabilities/refresh',
    devSimulateTurn: '/dev/simulate-turn',
    update: '/update',
    updateRestart: '/update/restart',
    updateStatus: '/update/status',
    macApps: '/mac-apps',
    mcpCatalog: '/mcp/catalog',
    mcpCatalogInstall: '/mcp/catalog/install',
    mcpServer: (name: string) => `/mcp/servers/${encodeURIComponent(name)}`,
    mcpServerEnabled: (name: string) => `/mcp/servers/${encodeURIComponent(name)}/enabled`,
    mcpServerTest: (name: string) => `/mcp/servers/${encodeURIComponent(name)}/test`,
    mcpServers: '/mcp/servers',
    modelAccess: '/model-access',
    modelAccessApiKey: '/model-access/api-key',
    modelAccessOAuthCancel: (sessionId: string) =>
        `/model-access/oauth/sessions/${encodeURIComponent(sessionId)}`,
    modelAccessOAuthPoll: (providerId: string, sessionId: string) =>
        `/model-access/oauth/${encodeURIComponent(providerId)}/poll/${encodeURIComponent(sessionId)}`,
    modelAccessOAuthStart: (providerId: string) =>
        `/model-access/oauth/${encodeURIComponent(providerId)}/start`,
    modelAccessOAuthSubmit: (providerId: string) =>
        `/model-access/oauth/${encodeURIComponent(providerId)}/submit`,
    modelAccessOpenAiSettings: '/model-access/openai',
    modelAccessOpenRouterSettings: '/model-access/openrouter',
    memorySettings: '/memory/settings',
    memoryAgentDream: (agentId: string) => `/memory/agents/${encodeURIComponent(agentId)}/dream`,
    memoryActivity: '/memory/activity',
    memoryJob: (jobId: string) => `/memory/jobs/${encodeURIComponent(jobId)}`,
    memoryJobs: '/memory/jobs',
    modelCapabilitySelections: '/model-capabilities/selections',
    modelCategorySettings: '/model-categories/settings',
    modelProvider: (providerId: string) => `/model-providers/${encodeURIComponent(providerId)}`,
    modelProvidersCatalog: '/model-providers/catalog',
    modelProvidersEnabled: '/model-providers/enabled',
    agentEnv: '/agent-env',
    timezoneSettings: '/timezone/settings',
    plugin: (id: string) => `/plugins/${encodeURIComponent(id)}`,
    pluginBrowserOpen: '/plugins/browser/open',
    pluginBrowserRestart: '/plugins/browser/restart',
    pluginBrowserSettings: '/plugins/browser/settings',
    pluginGoogleCalendarEvents: '/plugins/google/calendar/events',
    pluginGoogleDisconnect: '/plugins/google/oauth/disconnect',
    pluginGoogleOAuthComplete: (sessionId: string) =>
        `/plugins/google/oauth/sessions/${encodeURIComponent(sessionId)}/complete`,
    pluginGoogleOAuthPoll: (sessionId: string) =>
        `/plugins/google/oauth/sessions/${encodeURIComponent(sessionId)}`,
    pluginGoogleOAuthStart: '/plugins/google/oauth/start',
    pluginGoogleSettings: '/plugins/google/settings',
    pluginMerchbaseAction: '/plugins/merchbase/action',
    pluginMerchbaseSalesSeries: '/plugins/merchbase/sales/series',
    pluginMerchbaseSettings: '/plugins/merchbase/settings',
    plugins: '/plugins',
    job: (slug: string) => `/jobs/${encodeURIComponent(slug)}`,
    jobRun: (slug: string) => `/jobs/${encodeURIComponent(slug)}/run`,
    jobs: '/jobs',
    agentEngineConfig: '/agent-engine/config',
    cronJob: (id: string) => `/cron-jobs/${id}`,
    cronJobs: '/cron-jobs',
    cronJobRun: (id: string) => `/cron-jobs/${id}/run`,
    cronJobRuns: (id: string) => `/cron-jobs/${id}/runs`,
    cronRun: (id: string) => `/cron-runs/${id}`,
    cronRuns: '/cron-runs',
    label: (id: string) => `/labels/${encodeURIComponent(id)}`,
    labels: '/labels',
    task: (id: string) => `/tasks/${encodeURIComponent(id)}`,
    taskAttachment: (taskId: string, attachmentId: string) =>
        `/tasks/${encodeURIComponent(taskId)}/attachments/${encodeURIComponent(attachmentId)}`,
    taskDispatch: (id: string) => `/tasks/${encodeURIComponent(id)}/dispatch`,
    taskDispatchSettings: '/tasks/dispatch-settings',
    taskWorkChat: (id: string) => `/tasks/${encodeURIComponent(id)}/work-chat`,
    tasks: '/tasks',
    events: '/events',
    chatMessages: (chatId: string) => `/agent/chats/${chatId}/messages`,
    chatAgentSessionCurrent: (chatId: string) =>
        `/agent/chats/${encodeURIComponent(chatId)}/agent-sessions/current`,
    agentSessionReset: (agentId: string) =>
        `/agents/${encodeURIComponent(agentId)}/session/reset`,
    chatTurnStop: (chatId: string, runId: string) =>
        `/agent/chats/${encodeURIComponent(chatId)}/turns/${encodeURIComponent(runId)}/stop`,
    chatPaneState: (chatId: string) => `/agent/chats/${encodeURIComponent(chatId)}/pane-state`,
    chats: '/agent/chats',
    wikiBacklinks: (pagePath: string) => `/wiki/pages/${encodeURIComponent(pagePath)}/backlinks`,
    wikiFolder: (folderPath: string) => `/wiki/folders/${encodeURIComponent(folderPath)}`,
    wikiFolders: '/wiki/folders',
    wikiMovePath: '/wiki/move',
    wikiPage: (pagePath: string) => `/wiki/pages/${encodeURIComponent(pagePath)}`,
    wikiPages: '/wiki/pages',
    wikiSearch: '/wiki/search',
    wikiSettings: '/wiki/settings',
    wikiStatus: '/wiki/status',
    health: '/health',
    workspaceAgentInstructions: (agentId: string) =>
        `/workspace/agents/${encodeURIComponent(agentId)}/instructions`,
    workspaceAgentFile: (agentId: string, path: string) =>
        `/workspace/agents/${encodeURIComponent(agentId)}/files/${encodeURIComponent(path)}`,
    workspaceAgentFiles: (agentId: string) =>
        `/workspace/agents/${encodeURIComponent(agentId)}/files`,
    models: '/models',
    binding: (id: string) => `/bindings/${id}`,
    bindings: '/bindings',
    discordBinding: (id: string) => `/bindings/discord/${encodeURIComponent(id)}`,
    discordBindings: '/bindings/discord',
    skill: (id: string) => `/skills/${encodeURIComponent(id)}`,
    skillEnabled: (id: string) => `/skills/${id}/enabled`,
    skillReset: (id: string) => `/skills/${encodeURIComponent(id)}/reset`,
    skillHubAvailable: '/skills/hub/available',
    skillHubInstall: '/skills/hub/install',
    skillHubPreview: '/skills/hub/preview',
    skillHubScan: '/skills/hub/scan',
    skillHubTap: (repo: string) => `/skills/hub/taps/${encodeURIComponent(repo)}`,
    skillHubTaps: '/skills/hub/taps',
    skillHubUninstall: '/skills/hub/uninstall',
    skills: '/skills',
    tool: (id: string) => `/tools/${encodeURIComponent(id)}`,
    toolConfig: (id: string) => `/tools/${encodeURIComponent(id)}/config`,
    toolEnabled: (id: string) => `/tools/${encodeURIComponent(id)}/enabled`,
    toolEnv: (id: string) => `/tools/${encodeURIComponent(id)}/env`,
    toolPostSetup: (id: string) => `/tools/${encodeURIComponent(id)}/post-setup`,
    toolProvider: (id: string) => `/tools/${encodeURIComponent(id)}/provider`,
    tools: '/tools',
    sessionGraph: (sessionKey: string) => `/agent/sessions/${sessionKey}/graph`,
    sessionMessages: (sessionKey: string) => `/agent/sessions/${sessionKey}/messages`,
    sessionPrompt: (sessionKey: string) => `/agent/sessions/${sessionKey}/prompt`,
    sessionPreviews: '/agent/sessions/previews',
    sessionResync: (sessionKey: string) => `/agent/sessions/${sessionKey}/resync`,
    sessions: '/agent/sessions',
} as const;
