export const agentRuntimeMutationHeaders = {
    origin: 'x-tavern-origin',
} as const;

export const agentRuntimeMutationOrigins = {
    tavern: 'tavern',
    agentRuntime: 'agent-runtime',
} as const;

export const agentRuntimeRoutes = {
    agent: (id: string) => `/agents/${id}`,
    agentConfig: (id: string) => `/agents/${id}/config`,
    agentFile: (agentId: string, path: string) =>
        `/agents/${agentId}/files/${encodeURIComponent(path)}`,
    agentFiles: (agentId: string) => `/agents/${agentId}/files`,
    agentModel: (id: string) => `/agents/${id}/model`,
    agentName: (id: string) => `/agents/${id}/name`,
    agentThinkingDefault: (id: string) => `/agents/${id}/thinking-default`,
    agentTools: (id: string) => `/agents/${id}/tools`,
    agents: '/agents',
    capabilities: '/capabilities',
    capability: (id: string) => `/capabilities/${encodeURIComponent(id)}`,
    capabilityRefresh: (id: string) => `/capabilities/${encodeURIComponent(id)}/refresh`,
    capabilitiesRefresh: '/capabilities/refresh',
    commands: '/commands',
    commandsRun: '/commands/run',
    update: '/update',
    updateRestart: '/update/restart',
    updateStatus: '/update/status',
    macApps: '/mac-apps',
    mcpCatalog: '/mcp/catalog',
    mcpCatalogInstall: '/mcp/catalog/install',
    mcpServer: (name: string) => `/mcp/servers/${encodeURIComponent(name)}`,
    mcpServerEnabled: (name: string) => `/mcp/servers/${encodeURIComponent(name)}/enabled`,
    mcpServerTest: (name: string) => `/mcp/servers/${encodeURIComponent(name)}/test`,
    mcpServers: '/mcp/servers',
    modelAccess: '/model-access',
    modelAccessApiKey: '/model-access/api-key',
    modelAccessOAuthCancel: (sessionId: string) =>
        `/model-access/oauth/sessions/${encodeURIComponent(sessionId)}`,
    modelAccessOAuthPoll: (providerId: string, sessionId: string) =>
        `/model-access/oauth/${encodeURIComponent(providerId)}/poll/${encodeURIComponent(sessionId)}`,
    modelAccessOAuthStart: (providerId: string) =>
        `/model-access/oauth/${encodeURIComponent(providerId)}/start`,
    modelAccessOAuthSubmit: (providerId: string) =>
        `/model-access/oauth/${encodeURIComponent(providerId)}/submit`,
    modelAccessOpenAiSettings: '/model-access/openai',
    modelAccessOpenRouterSettings: '/model-access/openrouter',
    connector: (id: string) => `/connectors/${encodeURIComponent(id)}`,
    connectorTest: (id: string) => `/connectors/${encodeURIComponent(id)}/test`,
    connectors: '/connectors',
    agentEnv: '/agent-env',
    executionSettings: '/execution-settings',
    plugin: (id: string) => `/plugins/${encodeURIComponent(id)}`,
    pluginMerchbaseAction: '/plugins/merchbase/action',
    pluginMerchbaseSalesSeries: '/plugins/merchbase/sales/series',
    pluginMerchbaseSettings: '/plugins/merchbase/settings',
    plugins: '/plugins',
    permissionSettings: '/permission-settings',
    job: (slug: string) => `/jobs/${encodeURIComponent(slug)}`,
    jobRun: (slug: string) => `/jobs/${encodeURIComponent(slug)}/run`,
    jobs: '/jobs',
    hermesConfig: '/hermes-config',
    cronJob: (id: string) => `/cron-jobs/${id}`,
    cronJobs: '/cron-jobs',
    cronJobRun: (id: string) => `/cron-jobs/${id}/run`,
    cronJobRuns: (id: string) => `/cron-jobs/${id}/runs`,
    cronRun: (id: string) => `/cron-runs/${id}`,
    cronRuns: '/cron-runs',
    events: '/events',
    chatSocket: '/chat',
    chatMessages: (chatId: string) => `/hermes/chats/${chatId}/messages`,
    chatTurnSteer: (chatId: string, runId: string) =>
        `/hermes/chats/${encodeURIComponent(chatId)}/turns/${encodeURIComponent(runId)}/steer`,
    chatTurnStop: (chatId: string, runId: string) =>
        `/hermes/chats/${encodeURIComponent(chatId)}/turns/${encodeURIComponent(runId)}/stop`,
    chats: '/hermes/chats',
    vaultBacklinks: (pagePath: string) => `/vault/pages/${encodeURIComponent(pagePath)}/backlinks`,
    vaultFolder: (folderPath: string) => `/vault/folders/${encodeURIComponent(folderPath)}`,
    vaultFolders: '/vault/folders',
    vaultMovePath: '/vault/move',
    vaultPage: (pagePath: string) => `/vault/pages/${encodeURIComponent(pagePath)}`,
    vaultPages: '/vault/pages',
    vaultSearch: '/vault/search',
    vaultSettings: '/vault/settings',
    vaultStatus: '/vault/status',
    health: '/health',
    workspaceAgentInstructions: (agentId: string) =>
        `/workspace/agents/${encodeURIComponent(agentId)}/instructions`,
    models: '/models',
    binding: (id: string) => `/bindings/${id}`,
    bindings: '/bindings',
    discordBinding: (id: string) => `/bindings/discord/${encodeURIComponent(id)}`,
    discordBindings: '/bindings/discord',
    skillEnabled: (id: string) => `/skills/${id}/enabled`,
    skillHubAvailable: '/skills/hub/available',
    skillHubInstall: '/skills/hub/install',
    skillHubPreview: '/skills/hub/preview',
    skillHubScan: '/skills/hub/scan',
    skillHubTap: (repo: string) => `/skills/hub/taps/${encodeURIComponent(repo)}`,
    skillHubTaps: '/skills/hub/taps',
    skillHubUninstall: '/skills/hub/uninstall',
    skills: '/skills',
    toolsetConfig: (id: string) => `/toolsets/${encodeURIComponent(id)}/config`,
    toolsetEnabled: (id: string) => `/toolsets/${encodeURIComponent(id)}/enabled`,
    toolsetEnv: (id: string) => `/toolsets/${encodeURIComponent(id)}/env`,
    toolsetPostSetup: (id: string) => `/toolsets/${encodeURIComponent(id)}/post-setup`,
    toolsetProvider: (id: string) => `/toolsets/${encodeURIComponent(id)}/provider`,
    toolsets: '/toolsets',
    sessionApprovalRespond: (sessionKey: string) =>
        `/hermes/sessions/${encodeURIComponent(sessionKey)}/approval`,
    sessionClarificationRespond: (sessionKey: string) =>
        `/hermes/sessions/${encodeURIComponent(sessionKey)}/clarification`,
    sessionGraph: (sessionKey: string) => `/hermes/sessions/${sessionKey}/graph`,
    sessionMessages: (sessionKey: string) => `/hermes/sessions/${sessionKey}/messages`,
    sessionPrompt: (sessionKey: string) => `/hermes/sessions/${sessionKey}/prompt`,
    sessionPreviews: '/hermes/sessions/previews',
    sessionResync: (sessionKey: string) => `/hermes/sessions/${sessionKey}/resync`,
    sessions: '/hermes/sessions',
} as const;
