export const agentRuntimeMutationHeaders = {
    origin: 'x-tavern-origin',
} as const;

export const agentRuntimeMutationOrigins = {
    tavern: 'tavern',
    agentRuntime: 'agent-runtime',
} as const;

export const agentRuntimeRoutes = {
    agent: (id: string) => `/agents/${id}`,
    agentConfig: (id: string) => `/agents/${id}/config`,
    agentFile: (agentId: string, path: string) =>
        `/agents/${agentId}/files/${encodeURIComponent(path)}`,
    agentFiles: (agentId: string) => `/agents/${agentId}/files`,
    agents: '/agents',
    capabilities: '/capabilities',
    capability: (id: string) => `/capabilities/${encodeURIComponent(id)}`,
    capabilityRefresh: (id: string) => `/capabilities/${encodeURIComponent(id)}/refresh`,
    capabilitiesRefresh: '/capabilities/refresh',
    macApps: '/mac-apps',
    modelAccess: '/model-access',
    modelAccessOpenRouterSettings: '/model-access/openrouter',
    job: (slug: string) => `/jobs/${encodeURIComponent(slug)}`,
    jobRun: (slug: string) => `/jobs/${encodeURIComponent(slug)}/run`,
    jobs: '/jobs',
    openClawConfig: '/openclaw-config',
    cronJob: (id: string) => `/cron-jobs/${id}`,
    cronJobs: '/cron-jobs',
    cronJobRun: (id: string) => `/cron-jobs/${id}/run`,
    cronJobRuns: (id: string) => `/cron-jobs/${id}/runs`,
    cronRun: (id: string) => `/cron-runs/${id}`,
    cronRuns: '/cron-runs',
    events: '/events',
    chatSocket: '/chat',
    chatMessages: (chatId: string) => `/openclaw/chats/${chatId}/messages`,
    chats: '/openclaw/chats',
    cortexBacklinks: (slugOrId: string) =>
        `/cortex/pages/${encodeURIComponent(slugOrId)}/backlinks`,
    cortexCapture: '/cortex/capture',
    cortexJobRun: (job: string) => `/cortex/jobs/${encodeURIComponent(job)}/run`,
    cortexPage: (slugOrId: string) => `/cortex/pages/${encodeURIComponent(slugOrId)}`,
    cortexPages: '/cortex/pages',
    cortexRecall: '/cortex/recall',
    cortexSearch: '/cortex/search',
    cortexSettings: '/cortex/settings',
    cortexStatus: '/cortex/status',
    health: '/health',
    workspaceAgentInstructions: (agentId: string) =>
        `/workspace/agents/${encodeURIComponent(agentId)}/instructions`,
    workspaceAgentNotes: (agentId: string) =>
        `/workspace/agents/${encodeURIComponent(agentId)}/notes`,
    models: '/models',
    binding: (id: string) => `/bindings/${id}`,
    bindings: '/bindings',
    skillInstall: '/skills/install',
    skill: (id: string) => `/skills/${id}`,
    skillConfig: (id: string) => `/skills/${id}/config`,
    skills: '/skills',
    sessionGraph: (sessionKey: string) => `/openclaw/sessions/${sessionKey}/graph`,
    sessionMessages: (sessionKey: string) => `/openclaw/sessions/${sessionKey}/messages`,
    sessionPrompt: (sessionKey: string) => `/openclaw/sessions/${sessionKey}/prompt`,
    sessionPreviews: '/openclaw/sessions/previews',
    sessionResync: (sessionKey: string) => `/openclaw/sessions/${sessionKey}/resync`,
    sessions: '/openclaw/sessions',
} as const;
